In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import sklearn.preprocessing as preprocessing

In [2]:
df = pd.read_csv('risk_factors_cervical_cancer.csv')

In [3]:
df.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
2,34,1.0,?,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,?,?,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,?,?,0,0,0,0,0,0,0,0

In [21]:
df.describe()

,Age,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
count,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,26.820513,0.087413,0.020979,0.010490,0.020979,0.027972,0.040793,0.086247,0.051282,0.064103
std,8.497948,0.302545,0.143398,0.101939,0.143398,0.164989,0.197925,0.280892,0.220701,0.245078
min,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,32.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,84.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
#count the number of missing values in each column
df.isnull().sum()

Age                                   0
Number of sexual partners             0
First sexual intercourse              0
Num of pregnancies                    0
Smokes                                0
Smokes (years)                        0
Smokes (packs/year)                   0
Hormonal Contraceptives               0
Hormonal Contraceptives (years)       0
IUD                                   0
IUD (years)                           0
STDs                                  0
STDs (number)                         0
STDs:condylomatosis                   0
STDs:cervical condylomatosis          0
STDs:vaginal condylomatosis           0
STDs:vulvo-perineal condylomatosis    0
STDs:syphilis                         0
STDs:pelvic inflammatory disease      0
STDs:genital herpes                   0
STDs:molluscum contagiosum            0
STDs:AIDS                             0
STDs:HIV                              0
STDs:Hepatitis B                      0
STDs:HPV                              0
STDs: Number of diagnosis             0
STDs: Time since first diagnosis      0
STDs: Time since last diagnosis       0
Dx:Cancer                             0
Dx:CIN                                0
Dx:HPV                                0
Dx                                    0
Hinselmann                            0
Schiller                              0
Citology                              0
Biopsy                                0
dtype: int64

In [7]:
#show unique values in each column
for i in df.columns:
    print(i, df[i].unique())

Age [18 15 34 52 46 42 51 26 45 44 27 43 40 41 39 37 38 36 35 33 31 32 30 23
 28 29 20 25 21 24 22 48 19 17 16 14 59 79 84 47 13 70 50 49]
Number of sexual partners ['4.0' '1.0' '5.0' '3.0' '2.0' '6.0' '?' '7.0' '15.0' '8.0' '10.0' '28.0'
 '9.0']
First sexual intercourse ['15.0' '14.0' '?' '16.0' '21.0' '23.0' '17.0' '26.0' '20.0' '25.0' '18.0'
 '27.0' '19.0' '24.0' '32.0' '13.0' '29.0' '11.0' '12.0' '22.0' '28.0'
 '10.0']
Num of pregnancies ['1.0' '4.0' '2.0' '6.0' '3.0' '5.0' '?' '8.0' '7.0' '0.0' '11.0' '10.0']
Smokes ['0.0' '1.0' '?']
Smokes (years) ['0.0' '37.0' '34.0' '1.266972909' '3.0' '12.0' '?' '18.0' '7.0' '19.0'
 '21.0' '15.0' '13.0' '16.0' '8.0' '4.0' '10.0' '22.0' '14.0' '0.5' '11.0'
 '9.0' '2.0' '5.0' '6.0' '1.0' '32.0' '24.0' '28.0' '20.0' '0.16']
Smokes (packs/year) ['0.0' '37.0' '3.4' '2.8' '0.04' '0.5132021277' '2.4' '6.0' '?' '9.0'
 '1.6' '19.0' '21.0' '0.32' '2.6' '0.8' '15.0' '2.0' '5.7' '1.0' '3.3'
 '3.5' '12.0' '0.025' '2.75' '0.2' '1.4' '5.0' '2.1' '0.7' '1.2' '7.5'
 '1.25' '3.0' '0.75' '0.1' '8.0' '2.25' '0.003' '7.0' '0.45' '0.15' '0.05'
 '0.25' '4.8' '4.5' '0.4' '0.37' '2.2' '0.16' '0.9' '22.0' '1.35' '0.5'
 '2.5' '4.0' '1.3' '1.65' '2.7' '0.001' '7.6' '5.5' '0.3']
Hormonal Contraceptives ['0.0' '1.0' '?']
Hormonal Contraceptives (years) ['0.0' '3.0' '15.0' '2.0' '8.0' '10.0' '5.0' '0.25' '7.0' '22.0' '19.0'
 '0.5' '1.0' '0.58' '9.0' '13.0' '11.0' '4.0' '12.0' '16.0' '0.33' '?'
 '0.16' '14.0' '0.08' '2.282200521' '0.66' '6.0' '1.5' '0.42' '0.67'
 '0.75' '2.5' '4.5' '6.5' '0.17' '20.0' '3.5' '0.41' '30.0' '17.0']
IUD ['0.0' '1.0' '?']
IUD (years) ['0.0' '7.0' '?' '5.0' '8.0' '6.0' '1.0' '0.58' '2.0' '19.0' '0.5' '17.0'
 '0.08' '0.25' '10.0' '11.0' '3.0' '15.0' '12.0' '9.0' '1.5' '0.91' '4.0'
 '0.33' '0.41' '0.16' '0.17']
STDs ['0.0' '1.0' '?']
STDs (number) ['0.0' '2.0' '1.0' '?' '3.0' '4.0']
STDs:condylomatosis ['0.0' '1.0' '?']
STDs:cervical condylomatosis ['0.0' '?']
STDs:vaginal condylomatosis ['0.0' '?' '1.0']
STDs:vulvo-perineal condylomatosis ['0.0' '1.0' '?']
STDs:syphilis ['0.0' '1.0' '?']
STDs:pelvic inflammatory disease ['0.0' '?' '1.0']
STDs:genital herpes ['0.0' '?' '1.0']
STDs:molluscum contagiosum ['0.0' '?' '1.0']
STDs:AIDS ['0.0' '?']
STDs:HIV ['0.0' '1.0' '?']
STDs:Hepatitis B ['0.0' '?' '1.0']
STDs:HPV ['0.0' '?' '1.0']
STDs: Number of diagnosis [0 1 3 2]
STDs: Time since first diagnosis ['?' '21.0' '2.0' '15.0' '19.0' '3.0' '12.0' '1.0' '11.0' '9.0' '7.0'
 '8.0' '16.0' '6.0' '5.0' '10.0' '4.0' '22.0' '18.0']
STDs: Time since last diagnosis ['?' '21.0' '2.0' '15.0' '19.0' '3.0' '12.0' '1.0' '11.0' '9.0' '7.0'
 '8.0' '16.0' '6.0' '5.0' '10.0' '4.0' '22.0' '18.0']
Dx:Cancer [0 1]
Dx:CIN [0 1]
Dx:HPV [0 1]
Dx [0 1]
Hinselmann [0 1]
Schiller [0 1]
Citology [0 1]
Biopsy [0 1]

In [18]:
for i in df:
    print(i, df[i].value_counts())

Age 23    54
18    50
21    46
20    45
19    44
24    39
25    39
26    38
28    37
17    35
30    35
29    33
27    33
22    30
35    29
33    28
31    27
34    24
36    24
16    23
15    21
32    18
37    17
41    13
40    12
38     9
39     9
44     6
45     6
42     6
14     5
43     5
46     3
70     2
49     2
52     2
48     2
59     1
79     1
84     1
47     1
13     1
50     1
51     1
Name: Age, dtype: int64
Number of sexual partners 2.0     272
3.0     208
1.0     206
4.0      78
5.0      44
?        26
6.0       9
7.0       7
8.0       4
15.0      1
10.0      1
28.0      1
9.0       1
Name: Number of sexual partners, dtype: int64
First sexual intercourse 15.0    163
17.0    151
18.0    137
16.0    121
14.0     79
19.0     60
20.0     37
13.0     25
21.0     20
23.0      9
22.0      9
?         7
26.0      7
12.0      6
27.0      6
24.0      6
29.0      5
28.0      3
11.0      2
25.0      2
10.0      2
32.0      1
Name: First sexual intercourse, dtype: int64
Num of pregnancies 1.0     270
2.0     240
3.0     139
4.0      74
?        56
5.0      35
6.0      18
0.0      16
7.0       6
8.0       2
11.0      1
10.0      1
Name: Num of pregnancies, dtype: int64
Smokes 0.0    722
1.0    123
?       13
Name: Smokes, dtype: int64
Smokes (years) 0.0            722
1.266972909     15
?               13
5.0              9
9.0              9
1.0              8
3.0              7
2.0              7
16.0             6
7.0              6
8.0              6
11.0             5
10.0             5
4.0              5
15.0             4
14.0             4
6.0              4
13.0             3
0.5              3
19.0             3
12.0             3
22.0             2
32.0             1
20.0             1
28.0             1
24.0             1
18.0             1
34.0             1
37.0             1
21.0             1
0.16             1
Name: Smokes (years), dtype: int64
Smokes (packs/year) 0.0             722
0.5132021277     18
?                13
1.0               6
3.0               5
               ...
37.0              1
1.25              1
2.25              1
0.003             1
0.3               1
Name: Smokes (packs/year), Length: 63, dtype: int64
Hormonal Contraceptives 1.0    481
0.0    269
?      108
Name: Hormonal Contraceptives, dtype: int64
Hormonal Contraceptives (years) 0.0            269
?              108
1.0             77
0.25            41
2.0             40
3.0             39
5.0             34
0.08            25
0.5             25
6.0             24
4.0             22
7.0             21
8.0             18
0.16            16
9.0             12
10.0            11
0.33             9
0.42             8
0.75             7
0.66             6
0.58             6
15.0             6
20.0             4
12.0             4
1.5              3
0.67             2
11.0             2
2.282200521      2
14.0             2
19.0             2
13.0             2
16.0             2
22.0             1
2.5              1
4.5              1
6.5              1
0.17             1
3.5              1
0.41             1
30.0             1
17.0             1
Name: Hormonal Contraceptives (years), dtype: int64
IUD 0.0    658
?      117
1.0     83
Name: IUD, dtype: int64
IUD (years) 0.0     658
?       117
3.0      11
2.0      10
5.0       9
1.0       8
8.0       7
7.0       7
4.0       5
6.0       5
11.0      3
0.5       2
0.08      2
0.91      1
0.41      1
0.33      1
9.0       1
0.16      1
1.5       1
0.25      1
12.0      1
15.0      1
10.0      1
17.0      1
19.0      1
0.58      1
0.17      1
Name: IUD (years), dtype: int64
STDs 0.0    674
?      105
1.0     79
Name: STDs, dtype: int64
STDs (number) 0.0    674
?      105
2.0     37
1.0     34
3.0      7
4.0      1
Name: STDs (number), dtype: int64
STDs:condylomatosis 0.0    709
?      105
1.0     44
Name: STDs:condylomatosis, dtype: int64
STDs:cervical condylomatosis 0.0    753
?      105
Name: STDs:cervical condylomatosis, dtype: int64
STDs:vaginal condylomatosis 0.0    749
?      105
1.0      4
Name: STDs:vaginal condylomatosis, dtype: int64
STDs:vulvo-perineal condylomatosis 0.0    710
?      105
1.0     43
Name: STDs:vulvo-perineal condylomatosis, dtype: int64
STDs:syphilis 0.0    735
?      105
1.0     18
Name: STDs:syphilis, dtype: int64
STDs:pelvic inflammatory disease 0.0    752
?      105
1.0      1
Name: STDs:pelvic inflammatory disease, dtype: int64
STDs:genital herpes 0.0    752
?      105
1.0      1
Name: STDs:genital herpes, dtype: int64
STDs:molluscum contagiosum 0.0    752
?      105
1.0      1
Name: STDs:molluscum contagiosum, dtype: int64
STDs:AIDS 0.0    753
?      105
Name: STDs:AIDS, dtype: int64
STDs:HIV 0.0    735
?      105
1.0     18
Name: STDs:HIV, dtype: int64
STDs:Hepatitis B 0.0    752
?      105
1.0      1
Name: STDs:Hepatitis B, dtype: int64
STDs:HPV 0.0    751
?      105
1.0      2
Name: STDs:HPV, dtype: int64
STDs: Number of diagnosis 0    787
1     68
2      2
3      1
Name: STDs: Number of diagnosis, dtype: int64
STDs: Time since first diagnosis ?       787
1.0      15
3.0      10
2.0       9
4.0       6
7.0       5
16.0      4
5.0       4
8.0       3
6.0       3
19.0      2
11.0      2
21.0      2
10.0      1
22.0      1
9.0       1
12.0      1
15.0      1
18.0      1
Name: STDs: Time since first diagnosis, dtype: int64
STDs: Time since last diagnosis ?       787
1.0      17
2.0      10
3.0       9
4.0       6
7.0       5
16.0      4
5.0       3
8.0       3
6.0       3
11.0      2
21.0      2
22.0      1
10.0      1
9.0       1
12.0      1
19.0      1
15.0      1
18.0      1
Name: STDs: Time since last diagnosis, dtype: int64
Dx:Cancer 0    840
1     18
Name: Dx:Cancer, dtype: int64
Dx:CIN 0    849
1      9
Name: Dx:CIN, dtype: int64
Dx:HPV 0    840
1     18
Name: Dx:HPV, dtype: int64
Dx 0    834
1     24
Name: Dx, dtype: int64
Hinselmann 0    823
1     35
Name: Hinselmann, dtype: int64
Schiller 0    784
1     74
Name: Schiller, dtype: int64
Citology 0    814
1     44
Name: Citology, dtype: int64
Biopsy 0    803
1     55
Name: Biopsy, dtype: int64

In [20]:
for i in df:
    print(df[i].value_counts().loc[lambda x : x.index == '?'])

Series([], Name: Age, dtype: int64)
?    26
Name: Number of sexual partners, dtype: int64
?    7
Name: First sexual intercourse, dtype: int64
?    56
Name: Num of pregnancies, dtype: int64
?    13
Name: Smokes, dtype: int64
?    13
Name: Smokes (years), dtype: int64
?    13
Name: Smokes (packs/year), dtype: int64
?    108
Name: Hormonal Contraceptives, dtype: int64
?    108
Name: Hormonal Contraceptives (years), dtype: int64
?    117
Name: IUD, dtype: int64
?    117
Name: IUD (years), dtype: int64
?    105
Name: STDs, dtype: int64
?    105
Name: STDs (number), dtype: int64
?    105
Name: STDs:condylomatosis, dtype: int64
?    105
Name: STDs:cervical condylomatosis, dtype: int64
?    105
Name: STDs:vaginal condylomatosis, dtype: int64
?    105
Name: STDs:vulvo-perineal condylomatosis, dtype: int64
?    105
Name: STDs:syphilis, dtype: int64
?    105
Name: STDs:pelvic inflammatory disease, dtype: int64
?    105
Name: STDs:genital herpes, dtype: int64
?    105
Name: STDs:molluscum contagiosum, dtype: int64
?    105
Name: STDs:AIDS, dtype: int64
?    105
Name: STDs:HIV, dtype: int64
?    105
Name: STDs:Hepatitis B, dtype: int64
?    105
Name: STDs:HPV, dtype: int64
Series([], Name: STDs: Number of diagnosis, dtype: int64)
?    787
Name: STDs: Time since first diagnosis, dtype: int64
?    787
Name: STDs: Time since last diagnosis, dtype: int64
Series([], Name: Dx:Cancer, dtype: int64)
Series([], Name: Dx:CIN, dtype: int64)
Series([], Name: Dx:HPV, dtype: int64)
Series([], Name: Dx, dtype: int64)
Series([], Name: Hinselmann, dtype: int64)
Series([], Name: Schiller, dtype: int64)
Series([], Name: Citology, dtype: int64)
Series([], Name: Biopsy, dtype: int64)

In [22]:
#replace '?' with NaN
df.replace('?', np.nan, inplace=True)

In [33]:
df.dropna().shape[0]

59

In [38]:
#show rows where the columns 'IUD' has value np.nan
df.loc[df['IUD'].isnull()]

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
9,44,3.0,15.0,NaN,1.0,1.266972909,2.8,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
41,37,2.0,18.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,...,15.0,15.0,0,1,0,1,0,1,0,1
71,34,NaN,NaN,3.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
74,35,2.0,17.0,2.0,1.0,15.0,0.32,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
90,36,1.0,13.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,23,3.0,15.0,1.0,1.0,5.0,0.75,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
794,20,2.0,16.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
807,36,2.0,18.0,NaN,1.0,19.0,7.6,1.0,8.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
814,16,1.0,12.0,NaN,0.0,0.0,0.0,1.0,0.42,NaN,...,NaN,NaN,0,0,0,0,0,0,0,1
816,21,2.0,19.0,NaN,0.0,0.0,0.0,1.0,0.5,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0

In [70]:
#avg number of null values in each row that contains a null value in the column i
nan_dict={}
for i in df.columns:
    nan_dict[i] = df.loc[df[i].isnull()].isnull().sum(axis=1).mean()
print(nan_dict)

{'Age': nan, 'Number of sexual partners': 11.423076923076923, 'First sexual intercourse': 5.857142857142857, 'Num of pregnancies': 5.946428571428571, 'Smokes': 9.153846153846153, 'Smokes (years)': 9.153846153846153, 'Smokes (packs/year)': 9.153846153846153, 'Hormonal Contraceptives': 18.49074074074074, 'Hormonal Contraceptives (years)': 18.49074074074074, 'IUD': 18.11111111111111, 'IUD (years)': 18.11111111111111, 'STDs': 20.02857142857143, 'STDs (number)': 20.02857142857143, 'STDs:condylomatosis': 20.02857142857143, 'STDs:cervical condylomatosis': 20.02857142857143, 'STDs:vaginal condylomatosis': 20.02857142857143, 'STDs:vulvo-perineal condylomatosis': 20.02857142857143, 'STDs:syphilis': 20.02857142857143, 'STDs:pelvic inflammatory disease': 20.02857142857143, 'STDs:genital herpes': 20.02857142857143, 'STDs:molluscum contagiosum': 20.02857142857143, 'STDs:AIDS': 20.02857142857143, 'STDs:HIV': 20.02857142857143, 'STDs:Hepatitis B': 20.02857142857143, 'STDs:HPV': 20.02857142857143, 'STDs: Number of diagnosis': nan, 'STDs: Time since first diagnosis': 4.5578144853875475, 'STDs: Time since last diagnosis': 4.5578144853875475, 'Dx:Cancer': nan, 'Dx:CIN': nan, 'Dx:HPV': nan, 'Dx': nan, 'Hinselmann': nan, 'Schiller': nan, 'Citology': nan, 'Biopsy': nan}

In [73]:
df_reduce_nan = df
for key,val in nan_dict.items():
    if val > 2:
        df_reduce_nan.drop(key, axis=1, inplace=True)

In [74]:
df

,Age,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,0,0,0,0,0,0,0,0,0
1,15,0,0,0,0,0,0,0,0,0
2,34,0,0,0,0,0,0,0,0,0
3,52,0,1,0,1,0,0,0,0,0
4,46,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
853,34,0,0,0,0,0,0,0,0,0
854,32,0,0,0,0,0,0,0,0,0
855,25,0,0,0,0,0,0,0,1,0
856,33,0,0,0,0,0,0,0,0,0
857,29,0,0,0,0,0,0,0,0,0

In [75]:
#count null values in each column
df.isnull().sum()

Age                          0
STDs: Number of diagnosis    0
Dx:Cancer                    0
Dx:CIN                       0
Dx:HPV                       0
Dx                           0
Hinselmann                   0
Schiller                     0
Citology                     0
Biopsy                       0
dtype: int64

In [ ]:
### as we can see above, all rows containing a null value had greater than 2 null values.  It